runtime: python38 # or another supported version

instance_class: F1

env_variables:
  MYSQL_USER: root # please put in your credentials
  MYSQL_PASSWORD: 0ilmerchant # please put in your credentials
  MYSQL_DB: whatsgoodhere # please put in your credentials
  MYSQL_HOST: 35.188.84.202 # please put in your credentials
  INSTANCE_CONNECTION_NAME: composed-arbor-326120:us-central1:whats-good-here

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles